NordikAventure/Controllers/ProductController.cs
using GestBibli.Objects.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Nordik_Aventure.Objects.Models;
using Nordik_Aventure.Services;

namespace Nordik_Aventure.Controllers;

[Route("stock/products")]
public class ProductController : Controller
{
    private readonly ProductService _productService;
    private readonly SupplierService _supplierService;

    public ProductController(ProductService productService, SupplierService supplierService)
    {
        _productService = productService;
        _supplierService = supplierService;
    }

    [HttpGet]
    // Accéder a la page de tout les produits
    public IActionResult Index()
    {
        var result = _productService.GetAllProducts();
        return View("../ModuleStock/AllProducts", result.Data);
    }

    [HttpGet]
    [Route("add")]
    // Demande le formulaire d'ajout de produit
    public IActionResult AddProductForm()
    {
        var categories = _productService.GetAllCategories();
        var suppliers = _supplierService.GetAllSuppliers();
        var productVM = new ProductViewModel()
        {
            Categories = categories.Data,
            Suppliers = suppliers.Data,
        };
        return View("../ModuleStock/AddProduct", productVM);
    }

    [HttpPost]
    // Ajoute le produit
    public IActionResult AddProduct([FromForm] ProductViewModel productVM)
    {
        var product = new Product()
        {
            Name = productVM.Name,
            Sku = productVM.Sku,
            PriceToBuy = productVM.PriceToBuy,
            PriceToSell = productVM.PriceToSell,
            PaybackToSupplier = productVM.PaybackToSupplier,
            Weight = productVM.Weight,
            Status = productVM.Status,
            SupplierId = productVM.SelectedSupplierId,
            CategoryId = productVM.SelectedCategoryId,
            GrossMargin = Math.Round((productVM.PriceToSell - productVM.PriceToBuy) / productVM.PriceToSell * 100, 2),
            Description = productVM.Description,
        };
        var result = _productService.CreateProduct(product);
        if (!result.Success)
        {
            TempData["ErrorMessage"] = result.Message;
            TempData["ErrorType"] = "error";
            return RedirectToAction("AddProductForm");
        }

        TempData["ErrorType"] = "success";
        TempData["ErrorMessage"] = "Produit ajouté avec succès";
        return RedirectToAction("Index");
        
    }

    [HttpGet]
    [Route("edit/{productId}")]
    // Demande le formulaire de modification d'un produit
    public IActionResult ModifyProductForm(int productId)
    {
        var categories = _productService.GetAllCategories();
        var suppliers = _supplierService.GetAllSuppliers();
        var product = _productService.GetProductById(productId).Data;
        var productVM = new ProductViewModel()
        {
            Id = productId,
            Name = product.Name,
            Sku = product.Sku,
            PriceToBuy = product.PriceToBuy,
            PriceToSell = product.PriceToSell,
            PaybackToSupplier = product.PaybackToSupplier,
            Weight = product.Weight,
            Status = product.Status,
            SelectedCategoryId = product.CategoryId,
            SelectedSupplierId = product.SupplierId,
            Categories = categories.Data,
            Suppliers = suppliers.Data,
            Description = product.Description,
        };
        return View("../ModuleStock/ModifyProduct", productVM);
    }

    [HttpPost]
    [Route("edit")]
    // Modifie le produit
    public IActionResult ModifyProduct([FromForm] ProductViewModel productVM)
    {
        var existingProduct = _productService.GetProductById(productVM.Id).Data;
        existingProduct.Name = productVM.Name;
        existingProduct.PriceToSell = productVM.PriceToSell;
        existingProduct.PriceToBuy = productVM.PriceToBuy;
        existingProduct.Weight = productVM.Weight;
        existingProduct.Status = productVM.Status;
        existingProduct.CategoryId = productVM.SelectedCategoryId;
        existingProduct.SupplierId = productVM.SelectedSupplierId;
        existingProduct.PaybackToSupplier = productVM.PaybackToSupplier;
        existingProduct.GrossMargin =
            Math.Round((productVM.PriceToSell - productVM.PriceToBuy) / productVM.PriceToSell * 100, 2);
        existingProduct.Description = productVM.Description;
        var result = _productService.UpdateProduct(existingProduct);
        if (!result.Success)
        {
            TempData["ErrorMessage"] = result.Message;
            TempData["ErrorType"] = "error";
            return RedirectToAction("ModifyProductForm", new { productId = existingProduct.Id });
        }

        TempData["ErrorType"] = "success";
        TempData["ErrorMessage"] = "Produit modifié avec succès";
        return RedirectToAction("Index");
    }

}

NordikAventure/Controllers/StockMovementController.cs
using GestBibli.Objects;
using Microsoft.AspNetCore.Mvc;
using Nordik_Aventure.Objects.Models;
using Nordik_Aventure.Objects.Models.Finance;
using Nordik_Aventure.Services;

namespace Nordik_Aventure.Controllers;

[Route("stock/movement")]
public class StockMovementController : Controller
{
    private readonly MovementHistoryService _movementHistoryService;
    private readonly UserService _userService;
    private readonly UserSession _userSession;
    private readonly OrderService _orderService;
    private readonly SaleService _saleService;

    public StockMovementController(MovementHistoryService movementHistoryService, UserService userService,
        UserSession userSession, OrderService orderService, SaleService saleService)
    {
        _movementHistoryService = movementHistoryService;
        _userService = userService;
        _userSession = userSession;
        _orderService = orderService;
        _saleService = saleService;
    }

    [HttpGet]
    // Page d'accueil des mouvements dans le stock
    public IActionResult Index()
    {
        // Va chercher les 30 dernier movement historique
        var result = _movementHistoryService.GetLast30MovementHistory();
        if (!result.Success)
        {
            TempData["ErrorMessage"] = result.Message;
            TempData["ErrorType"] = "error";
            return RedirectToAction("Index", "Stock");
        }

        return View("../ModuleStock/StockMovement", result.Data);
    }

    // Permet de créer un mouvement de stock de type entrant
    public GenericResponse<MovementHistory> CreateEnteringStockMovement(int id)
    {
        // Va chercher l'id de l'employé présentement connecté
        var userId = _userSession.UserId;

        if (userId == null)
            return new GenericResponse<MovementHistory>("Aucun utilisateur connecté.", 401);

        // Va chercher la commande selon son Id
        var order = _orderService.GetOrderById(id);
        if (!order.Success)
            return new GenericResponse<MovementHistory>("Order not found", 404);
    
        var orderData = order.Data;
        // Va chercher les infos de l'employé connecté
        var currentEmployee = _userService.GetEmployeeById(userId.Value);

        // Construit le motif de la transaction automatiquement selon les produits qui ont été acheté
        var motifBuilder =
            $"{currentEmployee.Data.Name} {currentEmployee.Data.Surname} a acheté(e) le {orderData.DateOfOrdering:dd/MM/yyyy}: " +
            $"{string.Join("", orderData.OrderSupplierProducts.Select(osp => $"\n • {osp.Quantity} - {osp.Product.Name}"))} " +
            $"\npour un coût totale de {orderData.TotalPrice} $ (avec taxes)";

        var movementHistory = new MovementHistory()
        {
            Type = "purchase",
            Date = orderData.DateOfDelivery,
            Motif = motifBuilder,
            PurchaseId = orderData.PurchaseId,
            SaleId = null,
            EmployeeId = currentEmployee.Data.Id
        };

        return _movementHistoryService.AddEnteringMovementHistory(movementHistory);
    }
    
    // Même chose que plus haut, mais pour les mouvements sortants (ventes)
    public GenericResponse<MovementHistory> CreateLeavingStockMovement(int id)
    {
        var userId = _userSession.UserId;

        if (userId == null)
            return new GenericResponse<MovementHistory>("Aucun utilisateur connecté.", 401);

        var sale = _saleService.GetSaleById(id);
        if (!sale.Success)
            return new GenericResponse<MovementHistory>("Sale not found", 404);

        var saleData = sale.Data;
        var currentEmployee = _userService.GetEmployeeById(userId.Value);

        var motifBuilder =
            $"{currentEmployee.Data.Name} {currentEmployee.Data.Surname} a vendu(e) le {saleData.DateOfSale:dd/MM/yyyy}: " +
            $"{string.Join("", saleData.SaleDetails.Select(osp => $"\n • {osp.Quantity} - {osp.ProductInStock.Product.Name}"))} " +
            $"\npour un coût de {saleData.TotalPrice} $ (avec taxes)";

        var movementHistory = new MovementHistory()
        {
            Type = "sale",
            Date = DateTime.Now,
            Motif = motifBuilder,
            PurchaseId = null,
            SaleId = saleData.Id,
            EmployeeId = currentEmployee.Data.Id
        };

        return _movementHistoryService.AddLeavingMovementHistory(movementHistory);
    }
}

NordikAventure/Controllers/SupplierController.cs
using Microsoft.AspNetCore.Mvc;
using Nordik_Aventure.Objects.Models;
using Nordik_Aventure.Services;

namespace Nordik_Aventure.Controllers;

[Route("stock/supplier")]
public class SupplierController : Controller
{
    private readonly SupplierService _supplierService;
    public SupplierController(SupplierService supplierService)
    {
        _supplierService = supplierService;
    }

    [HttpGet]
    // Avoir la liste des fournisseurs
    public IActionResult Index()
    {
        var result = _supplierService.GetAllSuppliers();
        return View("../ModuleStock/AllSupplier", result.Data);
    }

    [HttpGet]
    [Route("add")]
    // Avoir le formulaire d'ajout d'un fournisseur
    public IActionResult AddSupplierForm()
    {
        return View("../ModuleStock/AddSupplier", new Supplier());
    }

    [HttpPost]
    [Route("add")]
    // Ajouter un fournisseur
    public IActionResult AddSupplier([FromForm] Supplier supplier)
    {
        var result = _supplierService.AddSupplier(supplier);
        if (!result.Success)
        {
            TempData["ErrorMessage"] = result.Message;
            TempData["ErrorType"] = "error";
            return View("../ModuleStock/AddSupplier", new Supplier());
        }
        
        TempData["ErrorMessage"] = "Fournisseur ajouté avec succès";
        TempData["ErrorType"] = "success";
        return View("../ModuleStock/AddSupplier", new Supplier());
    }
}

NordikAventure/Views/ModuleStock/AddProduct.cshtml
@model GestBibli.Objects.ViewModels.ProductViewModel
@{
    Layout = "_StockLayout";
}

<div class="container-fluid">
    <form id="form-add" method="post" asp-action="AddProduct" asp-controller="Product">
        <div class="row align-items-center mb-4">
            <div class="col">
                <h3 class="h3 mb-0 ms-2">Ajouter une fiche produit</h3>
            </div>
        </div>
        <hr/>
        <div class="cards-container">
            <div class="mb-3">
                <label asp-for="Sku" class="form-label"></label>
                <input asp-for="Sku" class="form-control" required="required"/>
                <span asp-validation-for="Sku" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Name" class="form-label">Nom</label>
                <input asp-for="Name" class="form-control" required="required"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="PriceToBuy" class="form-label">Prix d'achat</label>
                <input id="buy-price" type="number" step="0.01" min="0" max="99999" asp-for="PriceToBuy" class="form-control"/>
                <span asp-validation-for="PriceToBuy" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="PriceToSell" class="form-label">Prix de revente</label>
                <input id="sell-price" type="number" step="0.01" min="0" max="99999" asp-for="PriceToSell" class="form-control"/>
                <span asp-validation-for="PriceToSell" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="PaybackToSupplier" class="form-label">Remise au fournisseur (en décimal)</label>
                <input type="number" step="0.01" min="0" max="99999" asp-for="PaybackToSupplier" class="form-control"/>
                <span asp-validation-for="PaybackToSupplier" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Weight" class="form-label">Poid</label>
                <input type="number" step="0.01" min="0" max="99999" asp-for="Weight" class="form-control"/>
                <span asp-validation-for="Weight" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Description" class="form-label">Description</label>
                <input type="text" asp-for="Description" class="form-control"/>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="SelectedCategoryId" class="form-label">Catégorie</label>
                <select asp-for="SelectedCategoryId" class="form-select" aria-label="category">
                    @foreach (var c in @Model.Categories)
                    {
                        <option value="@c.Id">@c.Name</option>
                    }
                </select>
            </div>
            <div class="mb-3">
                <label asp-for="SelectedSupplierId" class="form-label">Fournisseur</label>
                <select asp-for="SelectedSupplierId" class="form-select" aria-label="supplier">
                    @foreach (var s in @Model.Suppliers)
                    {
                        <option value="@s.Id">@s.Name</option>
                    }
                </select>
            </div>
            <div class="mb-3">
                <label asp-for="Status" class="form-label">Statut</label>
                <select asp-for="Status" class="form-select" aria-label="status">
                    <option selected="selected" value="Actif">Disponible</option>
                    <option value="Non-Actif">Non-Disponible</option>
                </select>
            </div>
        </div>

        <div class="text-center mt-3">
            <button type="submit" style="background-color: var(--background-button); color: var(--text-white)" class="btn w-25">Confirmer</button>
        </div>
    </form>
</div>

<script>
    let form = document.getElementById("form-add");
    let buyPrice = document.getElementById("buy-price");
    let sellPrice = document.getElementById("sell-price");
    
    form.addEventListener("submit", (e) => {

        const buy = parseFloat(buyPrice.value);
        const sell = parseFloat(sellPrice.value);

        if (sell <= buy) {
            e.preventDefault();
            alert(`Le prix de vente doit être supérieur au prix d'achat`);
        }
    });
</script>

NordikAventure/Views/ModuleStock/AddSupplier.cshtml
@model Nordik_Aventure.Objects.Models.Supplier
@{
    Layout = "_StockLayout";
}

<div class="container-fluid">
    <form id="form-add" method="post" asp-action="AddSupplier" asp-controller="Supplier">
        <div class="row align-items-center mb-4">
            <div class="col">
                <h3 class="h3 mb-0 ms-2">Ajouter un fournisseur</h3>
            </div>
        </div>
        <hr/>
        <div class="cards-container">
            <div class="mb-3">
                <label asp-for="Name" class="form-label">Nom</label>
                <input asp-for="Name" class="form-control" required="required"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Code" class="form-label">Code</label>
                <input asp-for="Code" class="form-control" required="required"/>
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Discount" class="form-label">Rabais (%)</label>
                <input type="number" min="0" max="100" asp-for="Discount" class="form-control"/>
                <span asp-validation-for="Discount" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="AverageDeliveryTime" class="form-label">Délai moyen de livraison</label>
                <input asp-for="AverageDeliveryTime" class="form-control"/>
                <span asp-validation-for="AverageDeliveryTime" class="text-danger"></span>
            </div>
        </div>

        <div class="text-center mt-3">
            <button type="submit" style="background-color: var(--background-button); color: var(--text-white)" class="btn w-25">Confirmer</button>
        </div>
    </form>
</div>

NordikAventure/Views/ModuleStock/AllProducts.cshtml
@model List<Nordik_Aventure.Objects.Models.Product>
@{
    Layout = "_StockLayout";

    var list = Model;
}

<div class="container-fluid">
    <div class="row align-items-center mb-4">
        <div class="col">
            <h3 class="h3 mb-0 ms-2">Liste des fiches de produit</h3>
        </div>
        <div class="col text-end">
            <input id="searchInput" oninput="FilterList()" type="text" class="form-control w-50 d-inline-block" placeholder="Rechercher un produit..."/>
        </div>
    </div>
    <hr/>
    <div class="row mb-4 cards-container py-4 px-2">
        @foreach (var p in list)
        {
            <div class="col-md-6 mb-4" id="product-card-zone" data-name="@p.Name.ToLower()">
                <div class="product-card">
                    <div class="header">
                        <div class="info">
                            <p class="name">(@p.Sku) @p.Name</p>
                        </div>
                        <div class="status">
                            @if (p.Status == "Actif")
                            {
                                <span class="status-actif">● Actif</span>
                            }
                            else
                            {
                                <span class="status-inactif">● Inactif</span>
                            }
                        </div>
                    </div>

                    <div class="card-content">
                        <p><strong>Prix Achat:</strong> @p.PriceToBuy.ToString("F2") $</p>
                        <p><strong>Prix Vente:</strong> @p.PriceToSell.ToString("F2") $</p>
                        <p><strong>Marge Brute:</strong> @p.GrossMargin.ToString("F2") %</p>
                        <p>
                            <strong>Catégories:</strong> @p.Category.Name
                        </p>
                        <p><strong>Poids:</strong> @p.Weight kg</p>
                        <p>
                            <strong>Fournisseur:</strong> @p.Supplier.Name
                        </p>
                        <p style="text-overflow: ellipsis">
                            <strong>Description:</strong> @p.Description
                        </p>
                    </div>

                    <div class="text-center mt-2">
                        <a href=@Url.Action("ModifyProductForm", "Product", new { productId = p.Id }) class="btn w-50" style="background-color: var(--background-button); color: var(--text-white);">
                            Modifier
                        </a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

<script>
    function FilterList() {
        let word = document.getElementById("searchInput").value.toLowerCase();
        let cards = document.querySelectorAll("#product-card-zone");

        if (word.length === 0){
        cards.forEach(card => {
            card.style.display = "block"
        })
        }
        cards.forEach(card => {
            let name = card.getAttribute("data-name");
            card.style.display = name.startsWith(word) ? "block" : "none";
        });
    }
</script>

NordikAventure/Views/ModuleStock/AllSupplier.cshtml
@model List<Nordik_Aventure.Objects.Models.Supplier>
@{
    Layout = "_StockLayout";

    var list = Model;
}

<div class="container-fluid">
    <div class="row align-items-center mb-4">
        <div class="col">
            <h3 class="h3 mb-0 ms-2">Liste des fournisseurs</h3>
        </div>
        <div class="col text-end">
            <input id="searchInput" oninput="FilterList()" type="text" class="form-control w-50 d-inline-block" placeholder="Rechercher un produit..."/>
        </div>
    </div>
    <hr/>
    <div class="row mb-4 cards-container py-4 px-2">
        @foreach (var p in list)
        {
            <div class="col-md-6 mb-4" id="supplier-card-zone" data-name="@p.Name.ToLower()">
                <div class="product-card">
                    <div class="header">
                        <div class="info">
                            <p class="name">@p.Name</p>
                        </div>
                    </div>
                    <div class="card-content">
                        <p><strong>Code:</strong> @p.Code</p>
                    </div>
                    <div class="card-content">
                        <p><strong>Rabais:</strong> @p.Discount %</p>
                    </div>
                    <div class="card-content">
                        <p><strong>Délai moyen de livraison:</strong> @p.AverageDeliveryTime</p>
                    </div>
                    <div class="card-content">
                        <p><strong>Nombre de produits:</strong> @p.Products.Count</p>
                    </div>
                </div>
            </div>
        }
    </div>
    <hr/>
    <div class="row">
        <div class="col text-center">
            <a href="@Url.Action("AddSupplierForm", "Supplier")" class="btn w-25" style="background-color: var(--background-button); color: var(--text-white);">
                Ajouter un fournisseur
            </a>
        </div>
    </div>
</div>

<script>
    function FilterList() {
        let word = document.getElementById("searchInput").value.toLowerCase();
        let cards = document.querySelectorAll("#supplier-card-zone");

        if (word.length === 0){
        cards.forEach(card => {
            card.style.display = "block"
        })
        }
        cards.forEach(card => {
            let name = card.getAttribute("data-name");
            card.style.display = name.startsWith(word) ? "block" : "none";
        });
    }
</script>

NordikAventure/Views/ModuleStock/ModifyProduct.cshtml
@model GestBibli.Objects.ViewModels.ProductViewModel
@{
    Layout = "_StockLayout";
}

<div class="container-fluid">
    <form id="form-edit" method="post" asp-action="ModifyProduct" asp-controller="Product">
        <div class="row align-items-center mb-4">
            <div class="col">
                <h3 class="h3 mb-0 ms-2">Modifier le produit @Model.Name</h3>
            </div>
        </div>
        <hr/>
        <div class="cards-container">
            <div class="mb-3" style="display: none">
                <label asp-for="Id" class="form-label"></label>
                <input asp-for="Id" class="form-control" required="required"/>
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="mb-3" style="display: none">
                <label asp-for="Sku" class="form-label"></label>
                <input asp-for="Sku" class="form-control" required="required"/>
                <span asp-validation-for="Sku" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Name" class="form-label"></label>
                <input asp-for="Name" class="form-control" required="required"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="PriceToBuy" class="form-label"></label>
                <input id="buy-price" type="number" step="0.01" min="0" max="99999" asp-for="PriceToBuy" class="form-control"/>
                <span asp-validation-for="PriceToBuy" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="PriceToSell" class="form-label"></label>
                <input id="sell-price" type="number" step="0.01" min="0" max="99999" asp-for="PriceToSell" class="form-control"/>
                <span asp-validation-for="PriceToSell" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="PaybackToSupplier" class="form-label"></label>
                <input type="number" step="0.01" min="0" max="99999" asp-for="PaybackToSupplier" class="form-control"/>
                <span asp-validation-for="PaybackToSupplier" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Weight" class="form-label"></label>
                <input type="number" step="0.01" min="0" max="99999" asp-for="Weight" class="form-control"/>
                <span asp-validation-for="Weight" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Description" class="form-label"></label>
                <input type="text" asp-for="Description" class="form-control"/>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="SelectedCategoryId" class="form-label">Catégorie</label>
                <select asp-for="SelectedCategoryId" class="form-select" aria-label="category">
                    @foreach (var c in @Model.Categories)
                    {
                        <option value="@c.Id">@c.Name</option>
                    }
                </select>
            </div>
            <div class="mb-3">
                <label asp-for="SelectedSupplierId" class="form-label">Fournisseur</label>
                <select asp-for="SelectedSupplierId" class="form-select" aria-label="supplier">
                    @foreach (var s in @Model.Suppliers)
                    {
                        <option value="@s.Id">@s.Name</option>
                    }
                </select>
            </div>
            <div class="mb-3">
                <label asp-for="Status" class="form-label">Statut</label>
                <select asp-for="Status" class="form-select" aria-label="status">
                    <option selected="selected" value="Actif">Disponible</option>
                    <option value="Inactif">Non-Disponible</option>
                </select>
            </div>
        </div>

        <div class="text-center mt-3">
            <button type="submit" style="background-color: var(--background-button); color: var(--text-white)" class="btn w-25">Confirmer la modification</button>
        </div>
    </form>
</div>

<script>
    let form = document.getElementById("form-edit");
    let buyPrice = document.getElementById("buy-price");
    let sellPrice = document.getElementById("sell-price");
    
    form.addEventListener("submit", (e) => {

        const buy = parseFloat(buyPrice.value);
        const sell = parseFloat(sellPrice.value);

        if (sell <= buy) {
            e.preventDefault();
            alert(`Le prix de vente doit être supérieur au prix d'achat`);
        }
    });
</script>

NordikAventure/Views/ModuleStock/ModifyStockProduct.cshtml
@model Nordik_Aventure.Objects.Models.ProductInStock
@{
    Layout = "_StockLayout";
}

<div class="container-fluid">
    <form id="form-edit" method="post" asp-action="UpdateProductStock" asp-controller="Stock">
        <div class="row align-items-center mb-4">
            <div class="col">
                <h3 class="h3 mb-0 ms-2">Modifier le produit en stock @Model.Product.Name</h3>
            </div>
        </div>
        <hr/>
        <div class="cards-container">
            <div class="mb-3" style="display: none">
                <label asp-for="Id" class="form-label"></label>
                <input asp-for="Id" class="form-control" required="required"/>
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="QuantityInStock" class="form-label">Quantité en stock</label>
                <input id="quantityInput" type="number" min="0" asp-for="QuantityInStock" class="form-control"/>
                <span asp-validation-for="QuantityInStock" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Threshold" class="form-label">Seuil de réapprovisionnement</label>
                <input type="number" min="0" asp-for="Threshold" class="form-control"/>
                <span asp-validation-for="Threshold" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="MinimalQuantity" class="form-label">Quantité minimale</label>
                <input type="number" min="0" asp-for="MinimalQuantity" class="form-control"/>
                <span asp-validation-for="MinimalQuantity" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="StorageLocation" class="form-label">Emplacement</label>
                <input type="text" asp-for="StorageLocation" class="form-control"/>
                <span asp-validation-for="StorageLocation" class="text-danger"></span>
            </div>
            @if (Model.QuantityInStock <= 0)
            {
                <div class="mb-3" title="Impossible de changer le statut d'un objet avec une quantité à 0">
                    <label asp-for="Status" class="form-label">Statut</label>
                    <select disabled asp-for="Status" class="form-select" aria-label="status">
                        <option selected="selected" value="Inactif">Non-Disponible</option>
                    </select>
                    <input value="Inactif" asp-for="Status" hidden/>
                </div>
            }
            else
            {
                <div class="mb-3">
                    <label asp-for="Status" class="form-label">Statut</label>
                    <select asp-for="Status" class="form-select" aria-label="status">
                        <option value="Actif">Disponible</option>
                        <option value="Inactif">Non-Disponible</option>
                    </select>
                </div>
            }
        
        </div>

        <div class="text-center mt-3">
            <button type="submit" style="background-color: var(--background-button); color: var(--text-white)" class="btn w-25">Confirmer la modification</button>
        </div>
    </form>
</div>

<script>
    let hasInterractedOnce = false;
    let qteInput = document.getElementById('quantityInput')
    qteInput.addEventListener('click', () => {
        if (!hasInterractedOnce){
            alert("Vous devriez changer la quantité qu'en dernier recours. \nPour ajouter des produits dans le stock, passer par les commandes.")
            hasInterractedOnce = true
        }
    })

</script>